[package]
name = "dimensional_quantity"
version = "0.0.1-alpha.1"
edition = "2021"


[dependencies]
num-traits = "0.2.*"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.*"
num-traits = "0.2.*"
