name = "Angular jerk"
symbol = "AngularJerk"
snake_case_name = "angular_jerk"
short_dim_formula = "T<sup>-3</sup>⋅∠"
long_dim_formula = "Time<sup>-3</sup>⋅Angle"
units_formula = "s<sup>-3</sup>⋅rad"

[dimensions]
length = 0
mass = 0
time = -3
electric_current = 0
thermodynamic_temperature = 0
temperature_interval = 0
amount_of_substance = 0
luminous_intensity = 0
angle = 1
solid_angle = 0
information = 0

[units.RADIAN_PER_SECOND_CUBED]
multiplier = "1.0"
symbol = "rad/s³"
singular = "radian per second cubed"
plural = "radians per second cubed"

[units.DEGREE_PER_SECOND_CUBED]
multiplier = "1.745_329_251_994_329_5_E-2"
symbol = "°/s³"
singular = "degree per second cubed"
plural = "degrees per second cubed"

