name = "Electric charge to mass ratio"
symbol = "ElectricChargeToMassRatio"
snake_case_name = "electric_charge_to_mass_ratio"
short_dim_formula = "M<sup>-1</sup>⋅T<sup>1</sup>⋅I<sup>1</sup>"
long_dim_formula = "Mass<sup>-1</sup>⋅Time<sup>1</sup>⋅Electric current<sup>1</sup>"
units_formula = "kg<sup>-1</sup>⋅s<sup>1</sup>⋅A<sup>1</sup>"

[dimensions]
length = 0
mass = -1
time = 1
electric_current = 1
thermodynamic_temperature = 0
temperature_interval = 0
amount_of_substance = 0
luminous_intensity = 0
angle = 0 
solid_angle = 0
information = 0

[units.COULOMB_PER_KILOGRAM]
multiplier = "1.0E0"
symbol = "C/kg"
singular = "coulomb per kilogram"
plural = "couloms per kilogram"