name = "Electric charge to mass ratio"
symbol = "ElectricChargeToMassRatio"
snake_case_name = "electric_charge_to_mass_ratio"
short_dim_formula = "M<sub>-1</sub>⋅T<sub>1</sub>⋅I<sub>1</sub>"
long_dim_formula = "Mass<sub>-1</sub>⋅Time<sub>1</sub>⋅Electric current<sub>1</sub>"
units_formula = "kg<sub>-1</sub>⋅s<sub>1</sub>⋅A<sub>1</sub>"

[dimensions]
length = 0
mass = -1
time = 1
electric_current = 1
thermodynamic_temperature = 0
temperature_interval = 0
amount_of_substance = 0
luminous_intensity = 0
angle = 0 
solid_angle = 0
information = 0

[units.COULOMB_PER_KILOGRAM]
multiplier = "1.0E0"
symbol = "C/kg"
singular = "coulomb per kilogram"
plural = "couloms per kilogram"