name = "First radiation constant for spectral radiance"
symbol = "FirstRadiationConstantForSpectralRadiance"
snake_case_name = "first_radiation_constant_for_spectral_radiance"
short_dim_formula = "L<sup>4</sup>⋅M<sup>3</sup>⋅T<sup>-1</sup>⋅∠<sup>-2</sup>"
long_dim_formula = "Length<sup>4</sup>⋅Mass<sup>3</sup>⋅Time<sup>-1</sup>⋅Angle<sup>-2</sup>"
units_formula = "m<sup>4</sup>⋅kg<sup>3</sup>⋅s<sup>-1</sup>⋅rad<sup>-2</sup>"

[dimensions]
length = 4
mass = 3
time = -1
electric_current = 0
thermodynamic_temperature = 0
temperature_interval = 0
amount_of_substance = 0
luminous_intensity = 0
angle = 0
solid_angle = -1
information = 0

[units.WATT_SQUARE_METER_PER_STERADIAN]
multiplier = "1.0E0"
symbol = "W⋅m<sup>2</sup>/sr"
singular = "watt square meter per steradian"
plural = "watts square meter per steradian"