name = "Specific volume"
symbol = "SpecificVolume"
snake_case_name = "specific_volume"
short_dim_formula = "L<sup>3</sup>⋅M<sup>-1</sup>"
long_dim_formula = "Length<sup>3</sup>⋅Mass<sup>-1</sup>"
units_formula = "m<sup>3</sup>⋅kg<sup>-1</sup>"

[dimensions]
length = 3
mass = -1
time = 0
electric_current = 0
thermodynamic_temperature = 0
temperature_interval = 0
amount_of_substance = 0
luminous_intensity = 0
angle = 0 
solid_angle = 0
information = 0

[units.CUBIC_METER_PER_KILOGRAM]
multiplier = "1.0E0"
symbol = "m³/kg"
singular = "cubic meter per kilogram"
plural = "cubic meters per kilogram"

[units.CUBIC_CENTIMETER_PER_KILOGRAM]
multiplier = "1.0_E-6"
symbol = "cm³/kg"
singular = "cubic centimeter per kilogram"
plural = "cubic centimeters per kilogram"

[units.CUBIC_METER_PER_GRAM]
multiplier = "1.0_E+3"
symbol = "m³/g"
singular = "cubic meter per gram"
plural = "cubic meters per gram"

[units.CUBIC_CENTIMETER_PER_GRAM]
multiplier = "1.0_E-3"
symbol = "cm³/g"
singular = "cubic centimeter per gram"
plural = "cubic centimeters per gram"

