name = "Temperature coefficient"
symbol = "TemperatureCoefficient"
snake_case_name = "temperature_coefficient"
short_dim_formula = "`ΔTh`<sup>-1</sup>"
long_dim_formula = "Temperature interval<sup>-1</sup>"
units_formula = "ΔK<sup>-1</sup>"

[dimensions]
length = 0
mass = 0
time = 0
electric_current = 0
thermodynamic_temperature = 0
temperature_interval = -1
amount_of_substance = 0
luminous_intensity = 0
angle = 0 
solid_angle = 0
information = 0

[units.PER_KELVIN]
multiplier = "1.0E0"
symbol = "K⁻¹"
singular = "per kelvin"
plural = "per kelvin"

[units.PPM_PER_KELVIN]
multiplier = "1E-6"
symbol = "ppm/K"
singular = "ppm per kelvin"
plural = "ppm per kelvin"

[units.PPM_PER_DEGREE_CELSIUS]
multiplier = "1E-6"
symbol = "ppm/°C"
singular = "ppm per degree Celsius"
plural = "ppm per degree Celsius"

