name = "Thermal Conductance"
symbol = "ThermalConductance"
snake_case_name = "thermal_conductance"
short_dim_formula = "L<sup>2</sup>⋅M<sup>1</sup>⋅T<sup>-3</sup>⋅`ΔTh`<sup>-1</sup>"
long_dim_formula = "Length<sup>2</sup>⋅Mass<sup>1</sup>⋅Time<sup>-3</sup>⋅Temperature interval<sup>-1</sup>"
units_formula = "m<sup>2</sup>⋅kg<sup>1</sup>⋅s<sup>-3</sup>⋅`ΔK`<sup>-1</sup>"

[dimensions]
length = 2
mass = 1
time = -3
electric_current = 0
thermodynamic_temperature = 0
temperature_interval = -1
amount_of_substance = 0
luminous_intensity = 0
angle = 0 
solid_angle = 0
information = 0

[units.WATT_PER_KELVIN]
multiplier = "1.0"
symbol = "W/K"
singular = "watt per kelvin"
plural = "watts per kelvin"
