name = "Wien frequency displacement law constant"
symbol = "WienFrequencyDisplacementLawConstant"
snake_case_name = "wien_frequency_displacement_law_constant"
short_dim_formula = "T<sup>-1</sup>⋅Th<sup>-1</sup>"
long_dim_formula = "Time<sup>-1</sup>⋅Thermodynamic temperature<sup>-1</sup>"
units_formula = "s<sup>-1</sup>⋅K<sup>-1</sup>"

[dimensions]
length = 0
mass = 0
time = -1
electric_current = 0
thermodynamic_temperature = -1
temperature_interval = 0
amount_of_substance = 0
luminous_intensity = 0
angle = 0 
solid_angle = 0
information = 0

[units.HERTZ_PER_KELVIN]
multiplier = "1.0E0"
symbol = "Hz/K"
singular = "hertz per kelvin"
plural = "hertz per kelvin"
